# SPDX-FileCopyrightText: 2025 BlueZoo developers
# SPDX-License-Identifier: GPL-2.0-only

restylers:

  - name: whitespace

  - name: prettier-markdown
  - name: prettier-yaml
  - name: taplo  # TOML

  # Python formatters
  - name: ruff
    command:
      - ruff
      - check
      - --fix-only
  # NOTE: The order here matters. Automatic fixes should be applied
  #       before more general formatters like autopep8 and isort.
  - name: autopep8
  - name: isort
