# SPDX-FileCopyrightText: 2025 BlueZoo developers
# SPDX-License-Identifier: GPL-2.0-only
#
# This file is generated by scripts/bluez-interfaces.py
#
# Do not edit this file manually.
#

import sdbus


class MediaInterface(
        sdbus.DbusInterfaceCommonAsync,
        interface_name="org.bluez.Media1"):

    @sdbus.dbus_method_async(
        input_signature="oa{sv}",
        input_args_names=["endpoint", "properties"],
        result_signature="",
        result_args_names=[],
        flags=sdbus.DbusUnprivilegedFlag)
    async def RegisterEndpoint(
        self,
        endpoint: str,
        properties: dict[str, tuple[str, object]],
    ) -> None:
        raise NotImplementedError

    @sdbus.dbus_method_async(
        input_signature="o",
        input_args_names=["endpoint"],
        result_signature="",
        result_args_names=[],
        flags=sdbus.DbusUnprivilegedFlag)
    async def UnregisterEndpoint(
        self,
        endpoint: str,
    ) -> None:
        raise NotImplementedError

    @sdbus.dbus_method_async(
        input_signature="oa{sv}",
        input_args_names=["player", "properties"],
        result_signature="",
        result_args_names=[],
        flags=sdbus.DbusUnprivilegedFlag)
    async def RegisterPlayer(
        self,
        player: str,
        properties: dict[str, tuple[str, object]],
    ) -> None:
        raise NotImplementedError

    @sdbus.dbus_method_async(
        input_signature="o",
        input_args_names=["player"],
        result_signature="",
        result_args_names=[],
        flags=sdbus.DbusUnprivilegedFlag)
    async def UnregisterPlayer(
        self,
        player: str,
    ) -> None:
        raise NotImplementedError

    @sdbus.dbus_method_async(
        input_signature="oa{sv}",
        input_args_names=["root", "options"],
        result_signature="",
        result_args_names=[],
        flags=sdbus.DbusUnprivilegedFlag)
    async def RegisterApplication(
        self,
        root: str,
        options: dict[str, tuple[str, object]],
    ) -> None:
        raise NotImplementedError

    @sdbus.dbus_method_async(
        input_signature="o",
        input_args_names=["application"],
        result_signature="",
        result_args_names=[],
        flags=sdbus.DbusUnprivilegedFlag)
    async def UnregisterApplication(
        self,
        application: str,
    ) -> None:
        raise NotImplementedError

    @sdbus.dbus_property_async(
        property_signature="as",
        flags=sdbus.DbusPropertyEmitsChangeFlag)
    def SupportedUUIDs(self) -> list[str]:
        raise NotImplementedError

    @sdbus.dbus_property_async(
        property_signature="as",
        flags=sdbus.DbusPropertyEmitsChangeFlag)
    def SupportedFeatures(self) -> list[str]:
        raise NotImplementedError
