# SPDX-FileCopyrightText: 2025 BlueZoo developers
# SPDX-License-Identifier: GPL-2.0-only
#
# This file is generated by scripts/bluez-interfaces.py
#
# Do not edit this file manually.
#

import sdbus


class MediaEndpointInterface(
        sdbus.DbusInterfaceCommonAsync,
        interface_name="org.bluez.MediaEndpoint1"):

    @sdbus.dbus_method_async(
        input_signature="oa{sv}",
        input_args_names=["transport", "properties"],
        result_signature="",
        result_args_names=[],
        flags=sdbus.DbusUnprivilegedFlag)
    async def SetConfiguration(
        self,
        transport: str,
        properties: dict[str, tuple[str, object]],
    ) -> None:
        raise NotImplementedError

    @sdbus.dbus_method_async(
        input_signature="ay",
        input_args_names=["capabilities"],
        result_signature="ay",
        result_args_names=["r0"],
        flags=sdbus.DbusUnprivilegedFlag)
    async def SelectConfiguration(
        self,
        capabilities: bytes,
    ) -> bytes:
        raise NotImplementedError

    @sdbus.dbus_method_async(
        input_signature="a{sv}",
        input_args_names=["capabilities"],
        result_signature="a{sv}",
        result_args_names=["r0"],
        flags=sdbus.DbusUnprivilegedFlag)
    async def SelectProperties(
        self,
        capabilities: dict[str, tuple[str, object]],
    ) -> dict[str, tuple[str, object]]:
        raise NotImplementedError

    @sdbus.dbus_method_async(
        input_signature="o",
        input_args_names=["transport"],
        result_signature="",
        result_args_names=[],
        flags=sdbus.DbusUnprivilegedFlag)
    async def ClearConfiguration(
        self,
        transport: str,
    ) -> None:
        raise NotImplementedError

    @sdbus.dbus_method_async(
        input_signature="a{sv}",
        input_args_names=["properties"],
        result_signature="",
        result_args_names=[],
        flags=sdbus.DbusUnprivilegedFlag)
    async def Reconfigure(
        self,
        properties: dict[str, tuple[str, object]],
    ) -> None:
        raise NotImplementedError

    @sdbus.dbus_method_async(
        input_signature="",
        input_args_names=[],
        result_signature="",
        result_args_names=[],
        flags=sdbus.DbusUnprivilegedFlag)
    async def Release(
        self,
    ) -> None:
        raise NotImplementedError

    @sdbus.dbus_property_async(
        property_signature="s",
        flags=sdbus.DbusPropertyEmitsChangeFlag)
    def UUID(self) -> str:
        raise NotImplementedError

    @sdbus.dbus_property_async(
        property_signature="y",
        flags=sdbus.DbusPropertyEmitsChangeFlag)
    def Codec(self) -> int:
        raise NotImplementedError

    @sdbus.dbus_property_async(
        property_signature="u",
        flags=sdbus.DbusPropertyEmitsChangeFlag)
    def Vendor(self) -> int:
        raise NotImplementedError

    @sdbus.dbus_property_async(
        property_signature="ay",
        flags=sdbus.DbusPropertyEmitsChangeFlag)
    def Capabilities(self) -> bytes:
        raise NotImplementedError

    @sdbus.dbus_property_async(
        property_signature="ay",
        flags=sdbus.DbusPropertyEmitsChangeFlag)
    def Metadata(self) -> bytes:
        raise NotImplementedError

    @sdbus.dbus_property_async(
        property_signature="o",
        flags=sdbus.DbusPropertyEmitsChangeFlag)
    def Device(self) -> str:
        raise NotImplementedError

    @sdbus.dbus_property_async(
        property_signature="b",
        flags=sdbus.DbusPropertyEmitsChangeFlag)
    def DelayReporting(self) -> bool:
        raise NotImplementedError

    @sdbus.dbus_property_async(
        property_signature="u",
        flags=sdbus.DbusPropertyEmitsChangeFlag)
    def Locations(self) -> int:
        raise NotImplementedError

    @sdbus.dbus_property_async(
        property_signature="q",
        flags=sdbus.DbusPropertyEmitsChangeFlag)
    def SupportedContext(self) -> int:
        raise NotImplementedError

    @sdbus.dbus_property_async(
        property_signature="q",
        flags=sdbus.DbusPropertyEmitsChangeFlag)
    def Context(self) -> int:
        raise NotImplementedError

    @sdbus.dbus_property_async(
        property_signature="a{sv}",
        flags=sdbus.DbusPropertyEmitsChangeFlag)
    def QoS(self) -> dict[str, tuple[str, object]]:
        raise NotImplementedError

    @sdbus.dbus_property_async(
        property_signature="a{sv}",
        flags=sdbus.DbusPropertyEmitsChangeFlag)
    def SupportedFeatures(self) -> dict[str, tuple[str, object]]:
        raise NotImplementedError
