#!/usr/bin/env python3
# SPDX-FileCopyrightText: 2025 BlueZoo developers
# SPDX-License-Identifier: GPL-2.0-only

import re
from argparse import ArgumentParser, FileType

parser = ArgumentParser(description="Generate mappings for BlueZ D-Bus errors")
parser.add_argument("--output", type=FileType("w"), default="exceptions.py",
                    help="output file; defaults to %(default)s")
parser.add_argument("sources", metavar="FILE", type=FileType("r"), nargs="+",
                    help="input file(s)")

args = parser.parse_args()

# Regular expression to match BlueZ D-Bus errors.
re_error = re.compile(r"org\.bluez\.Error\.(\w+)")

errors = set()
# Read all files in the given directory and search for BlueZ D-Bus errors.
for source in args.sources:
    with source as f:
        for line in f:
            if match := re_error.search(line):
                errors.add(match.group(1))

TEMPLATE_HEADER = """
# SPDX-FileCopyrightText: 2025 BlueZoo developers
# SPDX-License-Identifier: GPL-2.0-only
#
# This file was generated by scripts/bluez-errors.py
#
# Do not edit this file manually.
#

import sdbus
"""

with args.output as f:
    f.write(TEMPLATE_HEADER.lstrip())
    for error in sorted(errors):
        f.write("\n\n")
        f.write(f"class DBusBluez{error}Error(sdbus.DbusFailedError):\n")
        f.write(f"    dbus_error_name = \"org.bluez.Error.{error}\"\n")
